# Generated by Django 3.1.7 on 2021-03-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='file_name',
            field=models.TextField(default='temp1.webm'),
        ),
    ]
