# Generated by Django 4.2.15 on 2024-08-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_videomodel_full_name_videomodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
